# Generated by Django 3.2.12 on 2022-02-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileface',
            name='picture1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='profileface',
            name='picture2',
            field=models.ImageField(upload_to=''),
        ),
    ]
