# Generated by Django 3.2.12 on 2022-02-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220217_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileface',
            name='picture1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profileface',
            name='picture2',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
