# Generated by Django 3.2.12 on 2022-02-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='sid',
            new_name='s_id',
        ),
    ]
