# Generated by Django 3.2.12 on 2022-02-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.travel_schedule'),
        ),
    ]
