# Generated by Django 3.2.12 on 2022-03-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(choices=[['Ford Bronco Outer Banks SUV 2021', 10], ['Ford Bronco Outer Banks SUV 2021', 10], ['Ford Bronco Sport Base SUV 2021', 9], ['Ford C-Max Energi Titanium Mini MPV', 1], ['Ford C-Max Grand MPV 2011', 2]], max_length=100)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
