# Generated by Django 3.2.12 on 2022-03-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('0', 'TVS'), ('1', 'BMW'), ('2', 'Hero'), ('3', 'Honda'), ('4', 'Bennelli')], max_length=11)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(choices=[('0', 'Ford Bronco Outer Banks SUV 2021'), ('1', 'Ford C-Max SEL Hybrid MPV 2013'), ('2', 'Ford Bronco Sport Base SUV 2021'), ('3', 'Ford C-Max Energi Titanium Mini MPV'), ('4', 'Ford C-Max Grand MPV 2011')], max_length=100),
        ),
    ]
