# Generated by Django 3.2.12 on 2022-03-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220305_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('0', 'TVS'), ('1', 'Germany'), ('2', 'United States'), ('3', 'Brazil'), ('4', 'Canada'), ('5', 'France'), ('6', 'RU')], max_length=20, unique=True)),
                ('popularity', models.IntegerField()),
            ],
        ),
    ]
